/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lojgkebqlffhbuzhbdmu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvamdrZWJxbGZmaGJ1emhiZG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMzE5OTAsImV4cCI6MjA3NTcwNzk5MH0.zLsy4hXb11vWAjyE6EcZU9-5YbRjBWukPFHA-voPK4g"